import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Card from '../components/Card'
import personas from '../personas.json'
import { useState, useEffect } from 'react'

const perfilDefault = {
  nombre:"Melina Robles",
  imagen:"https://definicion.de/wp-content/uploads/2019/06/perfildeusuario.jpg"
}



export default function Home() {
  const [perfil, setPerfil] = useState({});
  const darClick = (nombre, imagen) => {
    setPerfil({nombre, imagen})
  }
  useEffect(()=>{
    setPerfil(perfilDefault)
  },[])
  return (
    <div className={styles.container}>
      <Head>
        <title>Desafio 3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.menu}>
        <ul className={styles.menu_item}>
          <li className={styles.menu_titl} >Nombre: {perfil.nombre}</li>
          <li><img className={styles.menu_img} src={perfil.imagen}></img></li>
        </ul>
      </nav>

      <h1 className={styles.title}>
          PROBANDO HOOKS Y PROPS
        </h1>

      <main className={styles.main}>
        {personas.map(persona => <Card
        nombre={persona.nombre}
        descripcion={persona.descripcion}
        imagen={persona.imagen}
        funcion={darClick}
        />) }
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Luzmila Rodriguez{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
