import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Card from '../components/Card'
import elements from '../components/elements.json'
import ResponsiveAppBar from '../components/Navbar'
import Footer from '../components/Footer'

const perfilDefault = {
  nombre:"Melina Robles",
  imagen:"https://definicion.de/wp-content/uploads/2019/06/perfildeusuario.jpg"
}

export default function Home() {
  return (
    <div>
      <Head>
        <title>Desafío Semanal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ResponsiveAppBar/>

      <div className={styles.container}>
      {elements.map((element, key) => <Card 
      key={key}
      title={element.title} 
      descrip={element.descrip} 
      imagen={element.imagen} />) }
      </div>

      <Footer/>

    </div>
  )
}
